var actionTypes = {
  // Todo
  ALL_TODOS : 'ALL_TODOS',
  SINGLE_TODO : 'SINGLE_TODO',
  CREATE_TODO : 'CREATE_TODO',
  EDIT_TODO : 'EDIT_TODO',
  REMOVE_TODO : 'REMOVE_TODO',
  // Users
  ALL_USERS: 'ALL_USERS',
  SINGLE_USER: 'SINGLE_USER',
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER'
};

module.exports = {
  ...actionTypes,
};
